# 依赖
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Qu
tagline:          'Rocky's Blog'
description:      'Rocky's Blog'
url:              https://designqu.github.io/ 
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Rocky'
  url:            https://designqu.github.io/

paginate:         5

# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
sidebar_home_link:  true
github:
  repo:             https://github.com/DesignQu
