# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Qu
tagline:          'Android Engineer'
description:      'Android Engineer'
baseurl:          
url:              https://rockyqu.github.io

author:
  name:           'RockyQu'
  url:            https://github.com/RockyQu

paginate:         10

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:							https://github.com/RockyQu

# gitment
# enable: true
# id: '' #页面 ID, 可选。默认为 location.href
# owner: RockyQu
# repo: RockyQu.github.io #存储评论的 repo
# client_id: '04ac49f449da4aeb88be' #你的 Client ID
# client_secret: '0534d4a2359d843b61ff7bcb4c7728c222044881' #你的 Client secret