# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Qu
tagline:          'Android Engineer'
description:      'Android Engineer'
baseurl:          /
url:              https://rockyqu.github.io

author:
  name:           'Qu'
  url:            https://github.com/RockyQu

paginate:         10

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:							
repo:               https://github.com/RockyQu