# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Rocky
tagline:          '小曲的博客'
description:      '小曲的 <a href="https://designqu.github.io/" target="_blank">博客'
url:              https://designqu.github.io/ 
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Rocky'
  url:            https://designqu.github.io/

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
sidebar_home_link:  true
github:
  repo:             https://github.com/DesignQu
